// backend_tools/series_winners.js
window.seriesWinnersMaster = [
    { "year": 1993, "club": "Islwyn Running Club" },
    { "year": 1994, "club": "Islwyn Running Club" },
    { "year": 1995, "club": "Chepstow Harriers" },
    { "year": 1996, "club": "Cornelly Striders" },
    { "year": 1997, "club": "Fairwater Runners" },
    { "year": 1998, "club": "Rhondda Valley Runners" },
    { "year": 1999, "club": "Griffithstown Harriers" },
    { "year": 2000, "club": "Fairwater Runners" },
    { "year": 2002, "club": "Fairwater Runners" },
    { "year": 2003, "club": "Fairwater Runners" },
    { "year": 2004, "club": "Chepstow Harriers" },
    { "year": 2005, "club": "Chepstow Harriers" },
    { "year": 2006, "club": "Chepstow Harriers" },
    { "year": 2007, "club": "Chepstow Harriers" },
    { "year": 2009, "club": "Pontypridd Roadents" },
    { "year": 2010, "club": "Chepstow Harriers" },
    { "year": 2011, "club": "Fairwater Runners" },
    { "year": 2012, "club": "Fairwater Runners" },
    { "year": 2013, "club": "Chepstow Harriers" },
    { "year": 2014, "club": "Chepstow Harriers" },
    { "year": 2015, "club": "Pont-y-pwl & District Runners" },
    { "year": 2016, "club": "Chepstow Harriers" },
    { "year": 2017, "club": "Chepstow Harriers" },
    { "year": 2018, "club": "Pont-y-pwl & District Runners" },
    { "year": 2019, "club": "Chepstow Harriers" },
    { "year": 2022, "club": "Lliswerry Runners" },
    { "year": 2023, "club": "Parc Bryn Bach RC" },
    { "year": 2024, "club": "Lliswerry Runners" },
    { "year": 2025, "club": "Parc Bryn Bach RC" },
    { "year": 2026, "club": "Parc Bryn Bach RC" } 
];